### PR TITLE
Midi 119/classic tok

### PR DESCRIPTION
**Pull request by WojciechMat**
### MidiEncoder
I have implemented our classic one-token-per-note encoders and made them compatible with huggingface models.

I will conduct experiments which will help to recognize if the models (or T5 model for now) are capable of grasping hidden patterns and learning anything.

From there we can gradually increase difficulty of the task, while searching for optimal hyperparameters.

To run training with MidiEncoders you will need to run
```bash
python3 train.py tokens_per_note=single
```
### Initial experiment results
Model has reached slightly better loss and average distance than the one trained with MultiTokEncoders.
image
Average distance of 4.7 is rather satisfactory, but new sequences are still rather flat.
image

Perhaps the model would perform better if I were to use constant number of notes per sequence. 
BTW. T5 has basically the same architecture as our transformer from midi-translation, so I will also try to feed it data the same way we did in midi-translation project and see the results.

### CODE REVIEW

**Comment by roszcz** [comment]
> ### Initial experiment results
> Model has reached slightly better loss and average distance than the one trained with MultiTokEncoders. image Average distance of 4.7 is rather satisfactory, but new sequences are still rather flat. image

Can you add more details about what we're seeing here? If the model is predicting time information, it looks great, but if it's predicting only velocity, then it's kind of flat :)

**Comment by WojciechMat** [comment]
Yup, it is velocity only ://

**Comment by roszcz** [comment]
Right, in that case I would say that "4.7" distance is a non-satisfactory baseline that we should try to beat 🤔

**Comment by roszcz** [comment]
@WojciechMat Looks like the dashboard and download models scripts are not up to date, I'm getting this:

```sh
PYTHONPATH=. streamlit run dashboard/velocity/main.py
```

image

Let me know if I'm doing something wrong

**Comment by WojciechMat** [comment]
> @WojciechMat Looks like the dashboard and download models scripts are not up to date, I'm getting this:
> 
> ```shell
> PYTHONPATH=. streamlit run dashboard/velocity/main.py
> ```
> 
> image
> Let me know if I'm doing something wrong

Right, sorry, I will update it in a bit after I train some new model with different parameters and hopefully see some improvement.

**Pull request closed without merging**
